version: '3'
services:
  web:
    image: flask-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_PASS_FILE=/run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=mydb
    secrets:
      - db_password
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  pgdata:

secrets:
  db_password:
    file: db_password.txt

networks:
  app-network:
    driver: bridge
